# Defalut applications
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="chromium"

# Personal scripts path
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/bin/utils

# Emacs path
#export PATH=$PATH:~/.emacs.d/bin

# Rust path
#export PATH="$HOME/.cargo/bin:$PATH"

# Eww path
#export PATH="$HOME/eww/target/release:$PATH"

# NVM path
#source /usr/share/nvm/init-nvm.sh

# Yarn path
export PATH="$PATH:`yarn global bin`"

# Start xorg
startx
