# Defalut applications
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="chromium"

# Personal scripts path
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.local/bin/bar
export PATH=$PATH:$HOME/.local/bin/utils
export PATH=$PATH:$HOME/.local/bin/helpers

# Emacs path
#export PATH=$PATH:~/.emacs.d/bin

# Rust path
#export PATH="$HOME/.cargo/bin:$PATH"

# Eww path
export PATH="$HOME/eww/target/release:$PATH"

# NVM path
source /usr/share/nvm/init-nvm.sh

# Yarn path
export PATH="$PATH:`yarn global bin`"

export _JAVA_AWT_WM_NONREPARENTING=1

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Start xorg
#startx

