# Oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git zsh-autosuggestions)

# Oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.config/zsh/alias



