#!/bin/bash

hc() {
    herbstclient "$@"
}

# rules
hc unrule -F
hc rule focus=on
hc rule floatplacement=smart

hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
# hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
# hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DOCK|NOTIFICATION|DESKTOP)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off focus=off
hc set tree_style '╾│ ├└╼─┐'

hc rule class='code-oss' tag="DEV"
hc rule class='Chromium' tag="WEB"
hc rule class='firefox' tag="WEB"
hc rule class='TelegramDesktop' tag="TEL"

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done

# Set monitor size
herbstclient set_monitors 3840x2160+0+0

# unlock, just to be sure
hc unlock
