#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

hc() {
    herbstclient "$@"
}

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_padding 0
hc set frame_border_width 0
hc set frame_active_opacity 1
hc set frame_normal_opacity 1
hc set frame_transparent_width 0
hc set frame_bg_transparent 0
hc set frame_gap 0
hc set always_show_frame 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set window_gap 0

hc attr theme.title_height 0
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.urgent.border_width 1

hc attr theme.active.color "$color2"
hc attr theme.normal.color "$background"
hc attr theme.urgent.color "$color15"
hc attr theme.background_color  "$background"