#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

hc() {
    herbstclient "$@"
}

# theme 1
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_width 0
hc set frame_active_opacity 1
hc set frame_normal_opacity 1
hc set frame_transparent_width 0
hc set frame_bg_transparent 0
hc set frame_gap 0
hc set always_show_frame 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set window_gap 0

hc attr theme.title_height 0
hc attr theme.padding_top 50
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.urgent.border_width 0

hc attr theme.title_font 'Terminus (TTF):pixelsize=30:style=Bold'
hc attr theme.active.color "$color2"
hc attr theme.normal.color "$background"
hc attr theme.urgent.color "$color15"
hc attr theme.background_color  "$background"


# # theme 2
# hc attr theme.tiling.reset 1
# hc attr theme.floating.reset 1

# hc set frame_border_width 0
# hc set always_show_frame off
# hc set frame_bg_transparent off
# hc set frame_transparent_width 0
# hc set frame_gap 0

# hc attr theme.title_height 30
# hc attr theme.padding_top 10
# hc attr theme.title_font 'Terminus (TTF):pixelsize=30'
# hc attr theme.active.color "$color2"
# hc attr theme.title_color "$foreground"
# hc attr theme.normal.color "$background"
# hc attr theme.urgent.color "$color15"
# hc attr theme.normal.title_color "$foreground"
# hc attr theme.inner_width 0
# hc attr theme.inner_color black
# hc attr theme.border_width 0
# hc attr theme.floating.border_width 0
# hc attr theme.floating.outer_width 0
# hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color "$color2"
# hc attr theme.urgent.inner_color "$color15"
# # hc attr theme.normal.inner_color "$background"

# # copy inner color to outer_color
# for state in active urgent normal ; do
#     hc substitute C theme.${state}.inner_color \
#         attr theme.${state}.outer_color C
# done
# hc attr theme.active.outer_width 0
# hc attr theme.background_color "$background"

# hc set window_gap 0
# hc set frame_padding 0
# hc set smart_window_surroundings off
# hc set smart_frame_surroundings off
# hc set mouse_recenter_gap 0
