#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

xrandr

# merge in defaults and keymaps
xrdb -merge ~/.Xresources

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Set cursor
xsetroot -cursor_name left_ptr & > /dev/null

# Set wallpaper
theme_mgr & > /dev/null

# Start picom
#picom --experimental-backends & > /dev/null

# Start dunst 
dunst & > /dev/null

# Start sxhkd
sxhkd & > /dev/null

# Start eww
#eww daemon & > /dev/null

# Start dwm blocks
#dwmblocks & > /dev/null

# polybar
#~/.config/polybar/launch.sh & > /dev/null

# Start dwm
# while type dwm > /dev/null ; do dwm && continue || break ; done

# Start herbstluftwm
exec herbstluftwm --locked > /dev/null

# Start bspwm
# exec bspwm > /dev/null
