#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d DEV WEB FILES MUSIC VID

bspc config border_width         5
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a code-oss desktop='^1' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a jetbrains-studio state=floating
bspc rule -a TelegramDesktop desktop='^5' follow=on
bspc rule -a *:*:Emulator desktop=^3


