require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.nvim-tree"
require "user.lsp-config.language-server"
require "user.lsp-config.cmp-config"
-- require "user.colorscheme-config.nightfox"
require "user.colorscheme-config.pywal"
require "user.lualine-config"
require "user.barbar-config"
